<?php
// echo
// '<pre>',
// var_dump($this),
// '</pre>';

$weblog2 = Mage::getModel('complexworld/eavblogpost');
$entries = $weblog2->getCollection()
    ->addAttributeToSelect('title')
    ->addAttributeToSelect('date')
    ->addAttributeToSelect('content');
$entries->load();
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Olá Mundo Complexo</title>
    <style type="text/css">
        body {
            background-color:#DCDCDC;
        }
    </style>
</head>
<body>
    <h1>O complexo mundo do OpenMage</h1>
    <?php foreach ($entries as $entry) { ?>
        <h2><?php echo $entry->getTitle() ?></h2>
        <p>Date: <?php echo $entry->getDate() ?></p>
        <p><?php echo $entry->getContent() ?></p>
    <?php } ?>
</body>
</html>