<?php
    $this
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Olá Mundo Complexo</title>
    <style type="text/css">
        body {
            background-color:#808080;
        }
    </style>
</head>
<body>
    <h1>O mundo complexo do OpenMage</h1>
</body>
</html>